swagger: '2.0'
info:
  description: "This is the swagger file which describe every transactions between BACK-END and FRONT-END.\nThis aims to describes in depth objects that are used in Smart Mirror application"
  version: '1.0.0'
  title: 'Swagger Smart Mirror'
host: 'localhost:3000'

paths:
  /:
    get:
      description: Use it to see the best welcome message!
      responses:
        '200':
          description: a single string is returned

  /api/clock:
    get:
      description: Use to get the current date and time
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/Clock'
        '400':
          description: 'Invalid status value'

  /api/weather/current:
    get:
      description: Use to get the current weather from openweathermap
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/Weather'
        '400':
          description: 'Invalid status value'

  /api/weather/forecast:
    get:
      description: Use to get the current and the hourly weather from openweathermap
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/WeatherForecast'
        '400':
          description: 'Invalid status value'

  /api/news:
    get:
      description: Use to get the last newstitle from newsapi
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/News'
        '400':
          description: 'Invalid status value'

  /outlook:
    get:
      description: Use to connect on an outlook account
      responses:
        '200':
          description: a simple link is displayed to redirect on a microsoft connection page
        '400':
          description: 'Invalid status value'

  /outlook/auth:
    get:
      description: Use to connect on an outlook account
      responses:
        '200':
          description: allow to avoid the step with the link and then redirect on /outlook
        '400':
          description: 'Invalid status value'

  /outlook/calendar:
    get:
      description: Use to get the events on an outlook account
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/Outlook_calendar'
        '400':
          description: 'Invalid status value'

  /api/google/calendar:
    get:
      description: Use to get emails from Gmail account
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/Gmail'
        '400':
          description: 'Invalid status value'
  
  /api/bdd/account:
    get:
      description: Use to get all accounts from BDD
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/Accounts_list'
        '400':
          description: 'Invalid status value'

  /api/bdd/profile:
    get:
      description: Use to get list of profiles for a specific account from BDD
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/Profiles'
        '400':
          description: 'Invalid status value'

  /api/bdd/widget:
    get:
      description: Use to get all widgets from BDD
      responses:
        '200':
          description: a json is returned
          schema:
            $ref: '#/definitions/Widget'
        '400':
          description: 'Invalid status value'

  /api/bdd/account/register:
    post:
      summary: Creates a new account.
      consumes:
        - application/json
      parameters:
        - in: body
          name: name
          description: The account to create.
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        201:
          description: Accuont was created successfully
  
  /api/bdd/account/login:
    post:
      summary: Connect to account.
      consumes:
        - application/json
      parameters:
        - in: body
          name: name
          description: The account to connect.
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: Account connected

  /api/bdd/profile/register:
    post:
      summary: Creates a new profile.
      consumes:
        - application/json
      parameters:
        - in: body
          name: name
          description: The profile to create.
          schema:
            type: object
            required:
              - username
              - id_account
            properties:
              username:
                type: string
              id_account:
                type: integer
      responses:
        201:
          description: Profile was created successfully
  
  /api/bdd/profile/login:
    post:
      summary: Connect to profil.
      consumes:
        - application/json
      parameters:
        - in: body
          name: name
          description: The profile to connect.
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
      responses:
        201:
          description: Profile connected
  
definitions:
  Clock:
    type: object
    properties:
      dayname:
        type: string
        example: 'Lundi'
      monthname:
        type: string
        example: 'Mars'
      day:
        type: integer
        example: 28
      year:
        type: integer
        example: 2020
      hours:
        type: integer
        example: 14
      minutes:
        type: integer
        example: 58
      seconds:
        type: integer
        example: 34
  Weather:
    type: object
    properties:
      currenttemp:
        type: integer
        example: 19
      city:
        type: string
        example: 'Lille'
      iconurl:
        type: string
        example: 'http://openweathermap.org/img/w/10d.png'
  WeatherForecast:
    type: object
    properties:
      city:
        type: string
        example: 'Lille'
      current:
        temp:
          type: double
        sunrise:
          type: integer
        sunset:
          type: integer
        example:
          {
            'temp': 14.59,
            'sunrise': 1603347747,
            'sunset': 1603384896,
            'description': 'légère pluie',
            'iconurl': 'http://openweathermap.org/img/wn/10d.png',
          }
      hourly:
        example:
          $ref: '#/definitions/ArrayOfHourly'
      daily:
        example:
          $ref: '#/definitions/ArrayOfDaily'
  ArrayOfHourly:
    id:
      $ref: '#/definitions/Hourly'
  ArrayOfDaily:
    id:
      $ref: '#/definitions/Daily'
  Hourly:
    dt: 1601982000
    temp: 14.59
    description: 'légère pluie'
    iconurl: 'http://openweathermap.org/img/wn/10d.png'
  Daily:
    dt: 1603537200
    temp: 14.46
    description: 'légère pluie'
    iconurl: 'http://openweathermap.org/img/wn/10d.png'
  Gmail:
    type: object
    properties:
      sender:
        type: string
        example: 'francoishollande@gmail.com'
      object:
        type: string
        example: 'Wesh alors'
      sendingTime:
        type: string
        example: '20/02/1998 - 23h13'
      message:
        type: string
        example: 'Bonjour, cordialement wesh ahah'
  News:
    type: object
    properties:
      news:
        example:
          $ref: '#/definitions/ArrayOfNews'
  ArrayOfNews:
    0:
      type: array
      $ref: '#/definitions/NewsItem'
    1:
      type: array
      $ref: '#/definitions/NewsItem2'
  NewsItem:
    source: 'Francetvinfo.fr'
    title: 'Miss France 2021 : à peine élue, Anastasia Salvi, Miss Franche-Comté annonce sur Instagram renoncer à son titr - France 3 Régions'
  NewsItem2:
    source: "L'equipe"
    title: "Équipe de France : Olivier Giroud titulaire contre l'Ukraine - Foot - Bleus - L'Équipe.fr"
  Outlook_calendar:
    type: array
    items:
      type: array
      items:
        type: object
        properties:
          '@odata.etag':
            type: string
            example: 'W/"WlmYJULeyEiDlUMJkEu+vAAAA63umQ=="'
          'id':
            type: string
            example: 'AQMkADAwATY3ZmYAZS0xMGNiLWIxNjAtMDACLTAwCgBGAAADK92D3t4AbLZFmxY1izhjHhsHAFpZmCVC3shIg5VDCZBLvrwAAAIBDQAAAFpZmCVC3shIg5VDCZBLvrwAAAADrzeYAAAA'
          'subject':
            type: string
            example: 'coucou le mirroir'
          'start':
            type: object
            example:
              { 'dateTime': '2020-11-03T16:00:00.0000000', 'timeZone': 'UTC' }
          'end':
            type: object
            example:
              { 'dateTime': '2020-11-03T16:30:00.0000000', 'timeZone': 'UTC' }
          'organizer':
            type: object
            example:
              {
                'emailAddress':
                  {
                    'name': 'Adrien La Rafale',
                    'address': 'Mirroir-Connecte@hotmail.com',
                  },
              }
  Accounts:
    type: object
    properties:
      username:
        type: string
        example: Didier
      password:
        type: string
        example: 'azerty123'
  Accounts_list:
      type: object
      properties:
        'id':
          type: integer
          example: '1'
        'username':
          type: string
          example: 'Claire'
        'password':
          type: string
          example: 'azerty'
  Profiles:
    type: object
    properties:
      username:
        type: string
        example: Didier
      id_account:
        type: integer
        example: 1
  Widget:
    type: object
    properties:
      id:
        type: integer
        example: 1
      widget:
        type: string
        example: news
